version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/kubernetes/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/postman/"
    schedule:
      interval: "weekly"
